OPI-PIB/navoica-platform

- lms/static/sass/course-list.scss
- lms/templates/login-sidebar.html
Localhost login page sidebar FB link changed to icon.
> Added login page fb icon

- common/lib/xmodule/xmodule/capa_base.py
Poproszę o review. 
Ja wolałbym zostawić jak jest. No ale, zredukowałem ilość linii trackback do zera. Trackback odwoływał się i tak do linii kodu lms'a więc twórcom niczego nie dawał.
> [imp#1139] added trackbacklimit, and gettexted string: Staff debug info

- lms/djangoapps/discussion/templates/discussion/discussion_board_fragment.html
dodałem Enrollment entry point do fragmentu odpowiadającego za dyskusję. poproszę o review
> [FIX#961] added Enrollment webpack entry point to discussion fragment

- common/static/common/fontawesome-free/package.json
- lms/templates/courseware/course_about.html
- package-lock.json
Added time with date started course in about page/view
> added time with date started course in about page

- lms/templates/static_templates/contact.html
Reverts OPI-PIB/navoica-platform#98
> Revert "Feature/mooc 1196"

- lms/templates/dashboard.html
Changed filters to select only one checked filter and unchecked rest of them selected before. Changes on Ola's request.
> feature/mooc 1202 [changed]

- lms/static/sass/course-list.scss
- lms/templates/header/header.html
[hotfix] Course title inside header - font style changes
1. reverted to old version font styles on course title inside header
> Hotfix/mooc 1225 - font course title header

- common/lib/xmodule/xmodule/js/src/capa/display.js
- common/static/js/capa/src/formula_equation_preview.js
> mooc_1190 disabled submit button when mathjax is loading

- lms/envs/common.py
- lms/templates/courseware/course_about.html
- lms/templates/enroll_staff.html
- lms/templates/header/header.html
- lms/templates/main.html
- lms/templates/static_templates/legend.html
[IMP#1025] added header_navoica_logo_image setting
> [IMP#1025] added option to add individual og: tags for different urls

- lms/envs/common.py
- lms/static/js/discovery/models/course_discovery.js
[IMP#1282] added sorting by facet.count, only for language facet
> [IMP#1282] added language to COURSE_DISCOVERY_FILTERS list

- common/lib/xmodule/xmodule/js/src/sequence/display.js
Scroll window to nav-tabs element, after changing site content by left, right keyboard button event in Sequence xmodule
> MOOC-1291 Feat: scroll window to top after render

- common/djangoapps/student/views/dashboard.py
- lms/templates/dashboard.html
- lms/templates/enrollment/course_enrollment_message.html
Added course enrollment message when no course was enrolled
> [feature/mooc_1330] - enrollment message when no course was enrolled

- lms/templates/forgot_password_modal.html
MOOC-1266 Feat: Added email forgotten password validation
Blocked submit request if email is invalid
> MOOC-1266 Feat: Added email forgotten password validation

- lms/envs/common.py
- lms/static/js/course_info.js
- lms/static/js/courseware/get_course_progress.js
- lms/static/lms/fixtures/preview/course_preview.html
- lms/static/sass/course-list.scss
- lms/templates/courseware/course_about.html
- lms/templates/courseware/course_navigation.html
- lms/templates/preview_menu.html
- lms/templates/seq_module.html
- lms/urls.py
- requirements/edx/base.txt
- requirements/edx/development.txt
Implemented progress bar on course page and his tabs for current and changed user.
> MOOC-1320 Feat Add progress bar course

- lms/templates/courseware/course_about.html
https://jira.opi.org.pl/browse/MOOC-1386
> MOOC-1386 Fix: add correct Course difficulty translation

- cms/envs/k8s.py
- lms/envs/k8s.py
Dla Darka, zajawka settingsów dla k8s które później będą rozwijane o następne opcje
> add new settings file lms/cms for k8s

- requirements/edx/base.txt
- requirements/edx/development.txt
- requirements/edx/testing.txt
Niezamierzony start playera podczas włączania lekcji.
> Bugfix/Bump version of xblock-xblock in requirements to 1.1.1

- cms/templates/widgets/segment-io.html
- lms/templates/header/header.html
- lms/templates/index.html
- lms/templates/main.html
- lms/templates/preview_menu.html
MOOC-1261 Feat: remove wcag errors on homepage
> MOOC-1261 Feat: remove wcag errors on homepage

- lms/static/sass/course-list.scss
- lms/templates/courseware/course_about.html
- lms/templates/courseware/courses.html
- lms/templates/dashboard.html
- lms/templates/dashboard/_dashboard_course_listing.html
- lms/templates/forgot_password_modal.html
- lms/templates/header/header.html
- lms/templates/learner_dashboard/_dashboard_navigation_courses.html
- lms/templates/login.html
- lms/templates/preview_menu.html
- lms/templates/provider/authorize.html
- lms/templates/register.html
- lms/templates/static_templates/contact.html
- lms/templates/static_templates/honor.html
- lms/templates/static_templates/privacy.html
- lms/templates/student_account/account_settings.html
- openedx/features/course_bookmarks/templates/course_bookmarks/course-bookmarks.html
- openedx/features/course_experience/templates/course_experience/course-dates-fragment.html
- openedx/features/course_experience/templates/course_experience/course-home-fragment.html
- openedx/features/course_experience/templates/course_experience/course-outline-fragment.html
MOOC-1302 Feat: remove wcag errors from pages before log-in
> MOOC-1302 Feat: remove wcag errors from pages before log-in

- lms/templates/forgot_password_modal.html
Added for success message rest password accessibility for screen readers.
> MOOC-1268 Feat: add wcag accessibility success reset password

- conf/locale/en/LC_MESSAGES/mako.po
- conf/locale/pl/LC_MESSAGES/mako.po
- lms/templates/static_templates/honor.html
ten pull request należy zakończyć przez konsole
> MOOC-1427 Fix: merge honor site translations from develop branch

- conf/locale/en/LC_MESSAGES/mako.po
- lms/templates/static_templates/privacy.html
https://jira.opi.org.pl/browse/MOOC-1431
> MOOC-1431 Fix: add privacy page eng source strings

- conf/locale/en/LC_MESSAGES/mako.po
- lms/templates/static_templates/accessibility.html
tylko jeden plik .po  (z moimi nowymi frazami)
Proszę zwróć uwagę, że pozmieniane są numery linii. Nie wiem czy to czegoś nie popsuje na Transifexie.
> MOOC-1432 Fix: add accessibility page eng source strings

- lms/djangoapps/course_api/blocks/transformers/__init__.py
- lms/djangoapps/course_blocks/transformers/start_date.py
- openedx/features/course_experience/templates/course_experience/course-outline-fragment.html
- openedx/features/course_experience/utils.py
> Revert "#MOOC-1333 show all course menu"

- cms/envs/k8s.py
- lms/envs/k8s.py
read PLATFORM_VERSION from env BUILD_TAG, update handler for tracking; change facility
> Feat: Update k8s settings

- common/djangoapps/student/views/login.py
- conf/locale/en/LC_MESSAGES/django-partial.po
- lms/templates/login.html
> MOOC-1318 Fix: change error message text

- lms/static/js/course_info.js
- lms/static/js/courseware/get_course_progress.js
- lms/templates/courseware/course_navigation.html
- lms/templates/preview_menu.html
- webpack.common.config.js
Added update progress bar on submit answer and fired request on course page.
> MOOC-1403 Fix: add progress bar update

- lms/templates/register.html
Removed legacy validation confirm password and fixed validation form on confirm password.
> MOOC-1473 Fix: add fix on register page

- lms/templates/header/navbar-language-mobile.html
id language-mobile is not in use, do nothing, was left from old code
> MOOC-1538 Style: remove unused id language-mobile

- conf/locale/en/LC_MESSAGES/mako.po
- lms/static/sass/cookie-alert.scss
"Close the notice about use of cookies" new translation added to transifex
> MOOC-1300 Fix: add new translation for cookie banner

- requirements/edx/base.txt
- requirements/edx/development.txt
- requirements/edx/testing.txt
Accept first PR for xblock https://github.com/OPI-PIB/videojsXBlock/pull/2
> MOOC-1470: change version of videojs-xblock

- conf/locale/en/LC_MESSAGES/mako.po
- lms/templates/footer.html
- lms/templates/header/header.html
- lms/templates/login-sidebar.html
@krystianlygas prośba o sprawdzenie.
Założyłam nowy feature i zamknęłam poprzedni PR
https://github.com/OPI-PIB/navoica-platform/pull/431
> MOOC-1298 Style: change wcag in social icon

- lms/static/js/discovery/models/course_discovery.js
- lms/templates/courseware/courses.html
> MOOC-1741 Feat: add sorting courses by enrollment_start

- conf/locale/en/LC_MESSAGES/mako.po
- conf/locale/pl/LC_MESSAGES/mako.po
- lms/templates/static_templates/accessibility.html
@krystianlygas poproszę o sprawdzenie tłumaczeń
> MOOC-1878 Fix: update accessibility statement

- lms/static/sass/course-list.scss
- lms/static/sass/login.scss
@paula-opi proszę o sprawdzenie, fix - problemy ze stylowaniem stron logowanie i rejestracja
> MOOC-1748 Fix: add fixex style to login and registration page

- conf/locale/en/LC_MESSAGES/mako.po
- lms/static/js/tooltip_show.js
- lms/templates/register-form.html
- lms/templates/register.html
Wprowadziłam dodatkowo sprawdzenie w DOMie elementu tooltipu z progress baru, aby nie wywoływało się na każdej podstronie i nie krzyczało błędem.
> MOOC-2087 Feat: add confirm email input to register form
